### ISSUE TITLE
Segmentation fault (core dumped)... thoughts?

### ISSUE THREAD

**Issue by jlhanson5** [maartenmennes/ICA-AROMA#19]
Hello ICA-AROMA repo,

I'm trying to use ICA-AROMA on some 2mm data (already normalized to the MNI-152). I'm using the following syntax:

`python2.7 ~/Volumes/Hanson/Training_Resources/ICA-AROMA/ICA_AROMA.py -in ~/Volumes/Hanson/Duke_PAC/proc/140313_18263/fmri/rest/ICA_AROMA/20140313_18263_REST_LAS_st_mcfr_brain_MNI.nii.gz -o ~/Volumes/Hanson/Duke_PAC/proc/140313_18263/fmri/rest/ICA_AROMA/ -mc ~/Volumes/Hanson/Duke_PAC/proc/140313_18263/fmri/rest/20140313_18263_REST_LAS_st_mcfr_brain_norm.mat -m /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain_mask.nii.gz`

The program starts, and takes a while to output the following error:  

`Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/home/jamielh/Volumes/Hanson/Training_Resources/ICA-AROMA/ICA_AROMA.py", line 191, in <module>
    aromafunc.runICA(fslDir, inFile, outDir, melDir, mask, dim, TR)
  File "/home/jamielh/Volumes/Hanson/Training_Resources/ICA-AROMA/ICA_AROMA_functions.py", line 101, in runICA
    lenIC = int(float(subprocess.getoutput(cmd)))
ValueError: could not convert string to float: ERROR: Could not open file`

I've double-checked all the files are correctly named and exist. Other thoughts on things to troubleshoot? I'm presuming I'm hitting some sort of memory issue since the file is larger (due to the 2mmx2mmx2mm voxels). 

Jamie.

**Comment by maartenmennes** [comment]
Hello,
are the files executable? Sometimes FSL chokes on files not being executable, even though they are readable. The problem is with the thresh_zstat file (as per line 97 in ica_functions.py).
Maarten

**Comment by jlhanson5** [comment]
The files = the python code or the neuroimaging files? I think both are 777 (but our server sometimes bounces them back). I thought the segmentation core would be some sort of resource issue (like I'm out of memory, the file is too big to load into swap, etc.). I wonder if others have run into something similar?

**Comment by maartenmennes** [comment]
I'm referring to the neuroimaging files. According to the error message, it either does not exist or cannot be opened for some reason

**Comment by jlhanson5** [comment]
All files are executable (by me) and exist.

<img width="873" alt="dir" src="https://user-images.githubusercontent.com/7240261/33956095-942e9bae-e00b-11e7-8cbe-50360d37cf87.png">

Other thoughts?

**Comment by maartenmennes** [comment]
Do the thresh_zstat files exist in melodic.ica/stats?

In addition, it's always better to specify the full paths when running the AROMA command, i.e., replace ~ by /home/me/Volumes... Or whatever path it's located at. Sometimes these path references are not understood...
