### ISSUE TITLE
No denoised output

### ISSUE THREAD

**Issue by hhal** [maartenmennes/ICA-AROMA#23]
I've ran ICA-AROMA for many subjects with succes. However, for some subjects I don't find a denoised_fun_data output nifti in the subjects their melodic directory. The log report is not mentioning any errors, in fact it even says it 'finished'. 

Any ideas on what went wrong?

Thanks.

**Comment by maartenmennes** [comment]
most likely it cannot find the original non-denoised data for some reason. But without more detail this is hard to say. Alternatively, it fails at the fsl_regfilt stage because you might have too many noise components making the model rank deficient. We sometimes observe this with multiband, short TR, high volume count data.

**Comment by hhal** [comment]
Dear Maarten,

Thank you for your comments. Yes, what might be the case is that it has too many as noise labelled components, as I try to run it on a resting-state data set containing 1030 volumes (TR=2). Any idea on how to circumvent this?

**Comment by maartenmennes** [comment]
How many components in total does melodic return? With these high volume datasets, we typically advise to not use the automatic dimensionality estimation in melodic, but rather restrict the number of components to 100-150. In AROMA you can do this with the -dim option, provided you let AROMA run melodic (i.e,. you're not specifying a pre-calculated melodic directory).

**Comment by hhal** [comment]
In total the melodic sometimes returns over 400 components. I'll try to run them by fixing the dimensionality for melodic. Thanks for the suggestion.

**Comment by maartenmennes** [comment]
yes, in that case, you will benefit from 'combining' some noise into more encompassing components by reducing the ICA dimensionality. Good luck with your processing!
