### ISSUE TITLE
classification_plots matplotlib error

### ISSUE THREAD

**Issue by Virginiaconde** [maartenmennes/ICA-AROMA#28]
Hi all,

I'm having trouble running ICA-AROMA when it comes to the plot generation part. The first part (motion component identification) runs smoothly and I get an output of how many components have been classified as motion-related components. However something seems to go wrong with the classification_plots.py and matplotlib.

This is the error:

"Found 15 head motion-related components in a total of 41 components.
Traceback (most recent call last):
  File "/ifs/loni/faculty/thompson/four_d/TBI_all/NTNU/data_analysis/ICA-AROMA-master/ICA_AROMA.py", line 226, in <module>
    outDir)
  File "/ifs/loni/faculty/thompson/four_d/TBI_all/NTNU/data_analysis/ICA-AROMA-master/classification_plots.py", line 141, in classification_plot
    s=sizemarker)
  File "/usr/local/python-2.7.8/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 3635, in scatter
    collection.update(kwargs)
  File "/usr/local/python-2.7.8/lib/python2.7/site-packages/matplotlib/artist.py", line 757, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property data"

I have already upgraded matplotlib (within a virtualenv - I'm working from a server), but it doesn't seem to work.

Any advice will be greatly appreciated, thanks!
Virginia

**Comment by maartenmennes** [comment]
Hi Virginia,

have you solved this problem? It is very hard to troubleshoot for me from this end, as it is a matplotlib error, not an AROMA error. All I can say is that it works fine for me on python2.7 (2.7.14) and matplotlib version 2.1.0

Maarten

**Comment by maartenmennes** [comment]
ps. note that you can run classification_plots.py outside of the AROMA main script:

python2.7 ~/Scripts/ICA-AROMA/classification_plots.py -in classification_overview.txt

**Comment by Virginiaconde** [comment]
Hi Maarten,

Yes, I figured it’d be the case, no worries.
I don’t seem to make it work with my current matplotlib version but I’ll see what I can do to upgrade it.

Thanks for your reply!

Best wishes,
Virginia
