### ISSUE TITLE
MNI requirement

### ISSUE THREAD

**Issue by sgoksan** [maartenmennes/ICA-AROMA#34]
Hi, 

I guess this isn't really an issue but more of a question.
I'd like to use ICA-AROMA on my data but after reading the instructions it appears that there is a requirement for the data to have been registered to the MNI template brains. 

I have MRI data collected from 8-10 year old children and have therefore used a different template brain as my standard (Paediatric Template brains, also from the Montreal Neurological Institute: https://doi.org/10.1016/j.neuroimage.2010.07.033). 

I have run my preprocessing using FSL so I have *.feat/reg/ directories with the usual naming system (i.e. my standard.nii.gz image will be of my alternative template rather than the MNI152_T1_2mm_brain default). 

Can you please advise me whether ICA AROMA will still work adequately in this situation?
I have run some preliminary analysis and the components being labelled as noise do appear robust, however it have been unable to determine from the code whether there is anything more to consider.

I look forward to hearing back from you,
Thank you,
Sezgi

**Comment by maartenmennes** [comment]
Hello, the requirement for registration to MNI152 space is only related to masking of the brain edge or the CSF. So if your pediatric template has roughly the same outline as the MNI152 brain (which I'm expecting), you should be fine.
As an alternative, you could run AROMA with a registration to the MNI152 brain, and in addition, calculate the registration to your template. AROMA will output the denoised data in native space, you can then bring those to your template space.
