### ISSUE TITLE
Components classified, but no denoising 

### ISSUE THREAD

**Issue by sgoksan** [maartenmennes/ICA-AROMA#35]
Hi, I'm having a very similar problem to a previous user but I've tried downloading the most recent version of ICA-AROMA and I'm still not getting a denoised output. 

From the error output it appears that the code is not getting as far as Step 3) Data denoising:

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 
Step 1) MELODIC
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Traceback (most recent call last):
  File "/home/ICA-AROMA-master/ICA_AROMA.py", line 226, in <module>
    outDir)
  File "/home/ICA-AROMA-master/classification_plots.py", line 8, in classification_plot
    import matplotlib as mpl
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 127, in <module>
    from . import cbook
ImportError: cannot import name cbook

I hope you can help.
Thank you!

**Comment by maartenmennes** [comment]
there seems to be a problem with your matplotlib installation. Could you reinstall or upgrade matplotlib (that is what google suggests for your "ImportError: cannot import name cbook" error)

**Comment by sgoksan** [comment]
Hi, thank you for your response.

I've tried upgrading matplotlib but everything was already up to date. 
I then tried installing an older version of pip (2.0.2) and this time the denoising worked. Do you think this is an appropriate fix?

Thanks
Sezgi

**Comment by maartenmennes** [comment]
yes, the plotting is purely for illustration purposes and has no influence on the classification or denoising.
