### ISSUE TITLE
mouse fMRI data

### ISSUE THREAD

**Issue by khchuang** [maartenmennes/ICA-AROMA#36]
Hi, we're interested in applying this tool to remove artifacts in mouse fMRI data. It seems to require 3 masks in the template space. Particularly, how much margin is required for the mask_edge?

**Comment by maartenmennes** [comment]
Do I understand it correctly that you want to provide AROMA with new masks to do the classification? Not sure whether that will work given the nature of the LDA that makes the first feature. I'm not familiar with analyzing mouse fMRI data, so I'm not sure how much edge overlap would be appropriate in that case. But I'm guessing head motion will present itself similarly as in human data, i.e., in components that look like a rim around the head.
