### ISSUE TITLE
Smoothing prior to ICA-AROMA 

### ISSUE THREAD

**Issue by cjl2007** [maartenmennes/ICA-AROMA#37]
Hello - I have a question re: the requirement of spatial smoothing prior to running ICA-aroma. Is there a way that one can run ICA-aroma on unsmoothed data? 

As a bit of background, I am interested in comparing data that has been denoised using ICA-aroma vs. data that has gone through an alternative pipeline. I want the preprocessing steps performed in these two pipelines to be as similar as possible, so that any differences can be attributed to the different denoising strategies (and not preprocessing steps).

In the alternative pipeline, however, the data is denoised prior to any spatial smoothing. Spatial smoothing takes place after I have mapped the denoised data to a cortical surface (and data smoothed in geodesic space; not volumetric space). 

So, in the interested of making these two pipelines as comparable as possible, can you think of a way that I could get around having to run spatial smoothing prior to ICA-aroma? 

Any guidance would be appreciated, thank you
Chuck

**Comment by cjl2007** [comment]
As a quick follow up - I wanted to offer up the one idea that had occurred to me. Specifically, could one use smoothed data as the input to aroma, but then perform the denoising step on the unsmoothed data, using the components estimated from the smoothed data? In other words, editing  the "InFile" for the "denoising" function in ICA_AROMA_functions.py 

Thanks again, 
Chuck

**Comment by jspielb2** [comment]
I'm interested in doing the same thing - inputing smoothed data to ICA-AROMA, but carrying out denoising on un-smoothed data.  Maybe I missed a response, but is this possible?  Relatedly, is there a reason why this would be inappropriate to do?  Thanks!!

**Comment by maartenmennes** [comment]
Yes, that is possible, but not built-in. One way to go about it would be to run melodic on smoothed data. Then run ICA-AROMA on the unsmoothed data while providing the melodic folder you obtained earlier. AROMA will then use the ICA components from that folder to do its classification and remove selected components from your input data which are in this case unsmoothed.
