### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'ERROR: Could not open file'

### ISSUE THREAD

**Issue by GerardYu** [maartenmennes/ICA-AROMA#39]
Hi Maarten

i encountered the following error. Not sure what's wrong. Would greatly appreciate your help. Thanks in advance!

------------------------------- RUNNING ICA-AROMA -------------------------------
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' ---------------

Step 1) MELODIC
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
  - extracting the CSF & Edge fraction features
Traceback (most recent call last):
  File "../../ICA-AROMA/ICA_AROMA.py", line 213, in <module>
    edgeFract, csfFract = aromafunc.feature_spatial(fslDir, outDir, scriptDir, melIC_MNI)
  File "/bcs/projects/gerard_TDCSCogTraining/cross/REST/ICA-AROMA/ICA_AROMA_functions.py", line 359, in feature_spatial
    numICs = int(subprocess.getoutput('%sfslinfo %s | grep dim4 | head -n1 | awk \'{print $2}\'' % (fslDir, melIC) ))
ValueError: invalid literal for int() with base 10: 'ERROR: Could not open file'

**Comment by maartenmennes** [comment]
something is going wrong with your registration step and accordingly, it can't find the needed file. Check that your .feat directory contains all registrations steps etc.

**Comment by GerardYu** [comment]
i dont know if this is related but i ran the command 

"../../Python-2.7.16/python ../../ICA-AROMA/ICA_AROMA.py -in filtered_func_data.nii.gz -out ICA_AROMA -affmat reg/example_func2highres.nii.gz -warp reg/highres2standard_warp.nii.gz -mc mc/prefiltered_func_data_mcf.par"

in the subject's feat folder, and i got this:

"The specified input file does not exist.
The specified mc file does does not exist.
The specified affmat file does not exist.
The specified warp file does not exist."

However if i spell out the full path: 
"../../Python-2.7.16/python ../../ICA-AROMA/ICA_AROMA.py -in /bcs/projects/gerard_TDCSCogTraining/cross/REST/001/s1001REST.feat/filtered_func_data.nii.gz -out /bcs/projects/gerard_TDCSCogTraining/cross/REST/001/test -affmat /bcs/projects/gerard_TDCSCogTraining/cross/REST/001/s1001REST.feat/reg/example_func2highres.nii.gz -warp /bcs/projects/gerard_TDCSCogTraining/cross/REST/001/s1001REST.feat/reg/highres2standard_warp.nii.gz -mc /bcs/projects/gerard_TDCSCogTraining/cross/REST/001/s1001REST.feat/mc/prefiltered_func_data_mcf.par"

i am able to proceed with ICA-AROMA until the error at step 2 (as described in the original post).

I've checked that all these files exist in where they are supposed to be, and can be opened with viewers without any issues.

The feat preprocessing ran fine without any errors. I have pasted the output of find $pwd in the subject's feat directory below
./logs
./logs/feat1
./logs/feat9
./logs/feat0_init.o73098
./logs/feat0_init.e73098
./logs/feat1a_init
./logs/feat2_pre.o73856
./logs/feat2_pre.e73856
./logs/feat2_pre
./logs/feat5_stop.o80324
./logs/feat5_stop.e80324
./logs/feat0
./report_log.html
./design.fsf
./design.min
./design.frf
./design.mat
./design.trg
./design.con
./design_cov.ppm
./design_cov.png
./design.ppm
./design.png
./.files
./.files/fsl.css
./.files/images
./.files/images/fsl-macos-snapshot.tiff
./.files/images/fsl-bg
./.files/images/fslstart.jpg
./.files/images/fsl-bg.jpg
./.files/images/fsl-logo.png
./.files/images/fugue-bg.jpg
./.files/images/fsl-logo.gif
./.files/images/flirt-bg.jpg
./.files/images/fsl-logo.jpg
./.files/images/vert2.png
./.files/images/3.1r.jpg
./.files/images/fsl-logo-big.jpg
./.files/images/fslstart.png
./.files/images/tick.gif
./.files/images/3.jpg
./report_stats.html
./report_poststats.html
./example_func.nii.gz
./reg
./reg/example_func.nii.gz
./reg/highres.nii.gz
./reg/highres_head.nii.gz
./reg/standard.nii.gz
./reg/standard_head.nii.gz
./reg/standard_mask.nii.gz
./reg/example_func2highres_fast_wmseg.nii.gz
./reg/example_func2highres_fast_wmedge.nii.gz
./reg/example_func2highres_init.mat
./reg/example_func2highres.mat
./reg/example_func2highres.nii.gz
./reg/highres2example_func.mat
./reg/example_func2highres.png
./reg/highres2standard.mat
./reg/highres2standard_linear.nii.gz
./reg/highres_head_to_standard_head.log
./reg/highres2standard_warp.nii.gz
./reg/highres2highres_jac.nii.gz
./reg/highres2standard.nii.gz
./reg/standard2highres.mat
./reg/highres2standard.png
./reg/example_func2standard.mat
./reg/example_func2standard_warp.nii.gz
./reg/example_func2standard.nii.gz
./reg/standard2example_func.mat
./reg/example_func2standard1.png
./reg/example_func2standard.png
./report_unwarp.html
./report_reg.html
./mc
./mc/prefiltered_func_data_mcf.mat
./mc/prefiltered_func_data_mcf.mat/MAT_0000
./mc/prefiltered_func_data_mcf.mat/MAT_0001
./mc/prefiltered_func_data_mcf.mat/MAT_0002
./mc/prefiltered_func_data_mcf.mat/MAT_0003
./mc/prefiltered_func_data_mcf.mat/MAT_0004
./mc/prefiltered_func_data_mcf.mat/MAT_0005
./mc/prefiltered_func_data_mcf.mat/MAT_0006
./mc/prefiltered_func_data_mcf.mat/MAT_0007
./mc/prefiltered_func_data_mcf.mat/MAT_0008
./mc/prefiltered_func_data_mcf.mat/MAT_0009
./mc/prefiltered_func_data_mcf.mat/MAT_0010
./mc/prefiltered_func_data_mcf.mat/MAT_0011
./mc/prefiltered_func_data_mcf.mat/MAT_0012
./mc/prefiltered_func_data_mcf.mat/MAT_0013
./mc/prefiltered_func_data_mcf.mat/MAT_0014
./mc/prefiltered_func_data_mcf.mat/MAT_0015
./mc/prefiltered_func_data_mcf.mat/MAT_0016
./mc/prefiltered_func_data_mcf.mat/MAT_0017
./mc/prefiltered_func_data_mcf.mat/MAT_0018
./mc/prefiltered_func_data_mcf.mat/MAT_0019
./mc/prefiltered_func_data_mcf.mat/MAT_0020
./mc/prefiltered_func_data_mcf.mat/MAT_0021
./mc/prefiltered_func_data_mcf.mat/MAT_0022
./mc/prefiltered_func_data_mcf.mat/MAT_0023
./mc/prefiltered_func_data_mcf.mat/MAT_0024
./mc/prefiltered_func_data_mcf.mat/MAT_0025
./mc/prefiltered_func_data_mcf.mat/MAT_0026
./mc/prefiltered_func_data_mcf.mat/MAT_0027
./mc/prefiltered_func_data_mcf.mat/MAT_0028
./mc/prefiltered_func_data_mcf.mat/MAT_0029
./mc/prefiltered_func_data_mcf.mat/MAT_0030
./mc/prefiltered_func_data_mcf.mat/MAT_0031
./mc/prefiltered_func_data_mcf.mat/MAT_0032
./mc/prefiltered_func_data_mcf.mat/MAT_0033
./mc/prefiltered_func_data_mcf.mat/MAT_0034
./mc/prefiltered_func_data_mcf.mat/MAT_0035
./mc/prefiltered_func_data_mcf.mat/MAT_0036
./mc/prefiltered_func_data_mcf.mat/MAT_0037
./mc/prefiltered_func_data_mcf.mat/MAT_0038
./mc/prefiltered_func_data_mcf.mat/MAT_0039
./mc/prefiltered_func_data_mcf.mat/MAT_0040
./mc/prefiltered_func_data_mcf.mat/MAT_0041
./mc/prefiltered_func_data_mcf.mat/MAT_0042
./mc/prefiltered_func_data_mcf.mat/MAT_0043
./mc/prefiltered_func_data_mcf.mat/MAT_0044
./mc/prefiltered_func_data_mcf.mat/MAT_0045
./mc/prefiltered_func_data_mcf.mat/MAT_0046
./mc/prefiltered_func_data_mcf.mat/MAT_0047
./mc/prefiltered_func_data_mcf.mat/MAT_0048
./mc/prefiltered_func_data_mcf.mat/MAT_0049
./mc/prefiltered_func_data_mcf.mat/MAT_0050
./mc/prefiltered_func_data_mcf.mat/MAT_0051
./mc/prefiltered_func_data_mcf.mat/MAT_0052
./mc/prefiltered_func_data_mcf.mat/MAT_0053
./mc/prefiltered_func_data_mcf.mat/MAT_0054
./mc/prefiltered_func_data_mcf.mat/MAT_0055
./mc/prefiltered_func_data_mcf.mat/MAT_0056
./mc/prefiltered_func_data_mcf.mat/MAT_0057
./mc/prefiltered_func_data_mcf.mat/MAT_0058
./mc/prefiltered_func_data_mcf.mat/MAT_0059
./mc/prefiltered_func_data_mcf.mat/MAT_0060
./mc/prefiltered_func_data_mcf.mat/MAT_0061
./mc/prefiltered_func_data_mcf.mat/MAT_0062
./mc/prefiltered_func_data_mcf.mat/MAT_0063
./mc/prefiltered_func_data_mcf.mat/MAT_0064
./mc/prefiltered_func_data_mcf.mat/MAT_0065
./mc/prefiltered_func_data_mcf.mat/MAT_0066
./mc/prefiltered_func_data_mcf.mat/MAT_0067
./mc/prefiltered_func_data_mcf.mat/MAT_0068
./mc/prefiltered_func_data_mcf.mat/MAT_0069
./mc/prefiltered_func_data_mcf.mat/MAT_0070
./mc/prefiltered_func_data_mcf.mat/MAT_0071
./mc/prefiltered_func_data_mcf.mat/MAT_0072
./mc/prefiltered_func_data_mcf.mat/MAT_0073
./mc/prefiltered_func_data_mcf.mat/MAT_0074
./mc/prefiltered_func_data_mcf.mat/MAT_0075
./mc/prefiltered_func_data_mcf.mat/MAT_0076
./mc/prefiltered_func_data_mcf.mat/MAT_0077
./mc/prefiltered_func_data_mcf.mat/MAT_0078
./mc/prefiltered_func_data_mcf.mat/MAT_0079
./mc/prefiltered_func_data_mcf.mat/MAT_0080
./mc/prefiltered_func_data_mcf.mat/MAT_0081
./mc/prefiltered_func_data_mcf.mat/MAT_0082
./mc/prefiltered_func_data_mcf.mat/MAT_0083
./mc/prefiltered_func_data_mcf.mat/MAT_0084
./mc/prefiltered_func_data_mcf.mat/MAT_0085
./mc/prefiltered_func_data_mcf.mat/MAT_0086
./mc/prefiltered_func_data_mcf.mat/MAT_0087
./mc/prefiltered_func_data_mcf.mat/MAT_0088
./mc/prefiltered_func_data_mcf.mat/MAT_0089
./mc/prefiltered_func_data_mcf.mat/MAT_0090
./mc/prefiltered_func_data_mcf.mat/MAT_0091
./mc/prefiltered_func_data_mcf.mat/MAT_0092
./mc/prefiltered_func_data_mcf.mat/MAT_0093
./mc/prefiltered_func_data_mcf.mat/MAT_0094
./mc/prefiltered_func_data_mcf.mat/MAT_0095
./mc/prefiltered_func_data_mcf.mat/MAT_0096
./mc/prefiltered_func_data_mcf.mat/MAT_0097
./mc/prefiltered_func_data_mcf.mat/MAT_0098
./mc/prefiltered_func_data_mcf.mat/MAT_0099
./mc/prefiltered_func_data_mcf.mat/MAT_0100
./mc/prefiltered_func_data_mcf.mat/MAT_0101
./mc/prefiltered_func_data_mcf.mat/MAT_0102
./mc/prefiltered_func_data_mcf.mat/MAT_0103
./mc/prefiltered_func_data_mcf.mat/MAT_0104
./mc/prefiltered_func_data_mcf.mat/MAT_0105
./mc/prefiltered_func_data_mcf.mat/MAT_0106
./mc/prefiltered_func_data_mcf.mat/MAT_0107
./mc/prefiltered_func_data_mcf.mat/MAT_0108
./mc/prefiltered_func_data_mcf.mat/MAT_0109
./mc/prefiltered_func_data_mcf.mat/MAT_0110
./mc/prefiltered_func_data_mcf.mat/MAT_0111
./mc/prefiltered_func_data_mcf.mat/MAT_0112
./mc/prefiltered_func_data_mcf.mat/MAT_0113
./mc/prefiltered_func_data_mcf.mat/MAT_0114
./mc/prefiltered_func_data_mcf.mat/MAT_0115
./mc/prefiltered_func_data_mcf.mat/MAT_0116
./mc/prefiltered_func_data_mcf.mat/MAT_0117
./mc/prefiltered_func_data_mcf.mat/MAT_0118
./mc/prefiltered_func_data_mcf.mat/MAT_0119
./mc/prefiltered_func_data_mcf.mat/MAT_0120
./mc/prefiltered_func_data_mcf.mat/MAT_0121
./mc/prefiltered_func_data_mcf.mat/MAT_0122
./mc/prefiltered_func_data_mcf.mat/MAT_0123
./mc/prefiltered_func_data_mcf.mat/MAT_0124
./mc/prefiltered_func_data_mcf.mat/MAT_0125
./mc/prefiltered_func_data_mcf.mat/MAT_0126
./mc/prefiltered_func_data_mcf.mat/MAT_0127
./mc/prefiltered_func_data_mcf.mat/MAT_0128
./mc/prefiltered_func_data_mcf.mat/MAT_0129
./mc/prefiltered_func_data_mcf.mat/MAT_0130
./mc/prefiltered_func_data_mcf.mat/MAT_0131
./mc/prefiltered_func_data_mcf.mat/MAT_0132
./mc/prefiltered_func_data_mcf.mat/MAT_0133
./mc/prefiltered_func_data_mcf.mat/MAT_0134
./mc/prefiltered_func_data_mcf.mat/MAT_0135
./mc/prefiltered_func_data_mcf.mat/MAT_0136
./mc/prefiltered_func_data_mcf.mat/MAT_0137
./mc/prefiltered_func_data_mcf.mat/MAT_0138
./mc/prefiltered_func_data_mcf.mat/MAT_0139
./mc/prefiltered_func_data_mcf.mat/MAT_0140
./mc/prefiltered_func_data_mcf.mat/MAT_0141
./mc/prefiltered_func_data_mcf.mat/MAT_0142
./mc/prefiltered_func_data_mcf.mat/MAT_0143
./mc/prefiltered_func_data_mcf.mat/MAT_0144
./mc/prefiltered_func_data_mcf.mat/MAT_0145
./mc/prefiltered_func_data_mcf.mat/MAT_0146
./mc/prefiltered_func_data_mcf.mat/MAT_0147
./mc/prefiltered_func_data_mcf.mat/MAT_0148
./mc/prefiltered_func_data_mcf.mat/MAT_0149
./mc/prefiltered_func_data_mcf.mat/MAT_0150
./mc/prefiltered_func_data_mcf.mat/MAT_0151
./mc/prefiltered_func_data_mcf.mat/MAT_0152
./mc/prefiltered_func_data_mcf.mat/MAT_0153
./mc/prefiltered_func_data_mcf.mat/MAT_0154
./mc/prefiltered_func_data_mcf.mat/MAT_0155
./mc/prefiltered_func_data_mcf.mat/MAT_0156
./mc/prefiltered_func_data_mcf.mat/MAT_0157
./mc/prefiltered_func_data_mcf.mat/MAT_0158
./mc/prefiltered_func_data_mcf.mat/MAT_0159
./mc/prefiltered_func_data_mcf.mat/MAT_0160
./mc/prefiltered_func_data_mcf.mat/MAT_0161
./mc/prefiltered_func_data_mcf.mat/MAT_0162
./mc/prefiltered_func_data_mcf.mat/MAT_0163
./mc/prefiltered_func_data_mcf.mat/MAT_0164
./mc/prefiltered_func_data_mcf.mat/MAT_0165
./mc/prefiltered_func_data_mcf.mat/MAT_0166
./mc/prefiltered_func_data_mcf.mat/MAT_0167
./mc/prefiltered_func_data_mcf.mat/MAT_0168
./mc/prefiltered_func_data_mcf.mat/MAT_0169
./mc/prefiltered_func_data_mcf.mat/MAT_0170
./mc/prefiltered_func_data_mcf.mat/MAT_0171
./mc/prefiltered_func_data_mcf.mat/MAT_0172
./mc/prefiltered_func_data_mcf.mat/MAT_0173
./mc/prefiltered_func_data_mcf.mat/MAT_0174
./mc/prefiltered_func_data_mcf.mat/MAT_0175
./mc/prefiltered_func_data_mcf.mat/MAT_0176
./mc/prefiltered_func_data_mcf.mat/MAT_0177
./mc/prefiltered_func_data_mcf.mat/MAT_0178
./mc/prefiltered_func_data_mcf.mat/MAT_0179
./mc/prefiltered_func_data_mcf.mat/MAT_0180
./mc/prefiltered_func_data_mcf.mat/MAT_0181
./mc/prefiltered_func_data_mcf.mat/MAT_0182
./mc/prefiltered_func_data_mcf.mat/MAT_0183
./mc/prefiltered_func_data_mcf.mat/MAT_0184
./mc/prefiltered_func_data_mcf.mat/MAT_0185
./mc/prefiltered_func_data_mcf.mat/MAT_0186
./mc/prefiltered_func_data_mcf.mat/MAT_0187
./mc/prefiltered_func_data_mcf.mat/MAT_0188
./mc/prefiltered_func_data_mcf.mat/MAT_0189
./mc/prefiltered_func_data_mcf.mat/MAT_0190
./mc/prefiltered_func_data_mcf.mat/MAT_0191
./mc/prefiltered_func_data_mcf.mat/MAT_0192
./mc/prefiltered_func_data_mcf.mat/MAT_0193
./mc/prefiltered_func_data_mcf.mat/MAT_0194
./mc/prefiltered_func_data_mcf.mat/MAT_0195
./mc/prefiltered_func_data_mcf.mat/MAT_0196
./mc/prefiltered_func_data_mcf.mat/MAT_0197
./mc/prefiltered_func_data_mcf.mat/MAT_0198
./mc/prefiltered_func_data_mcf.mat/MAT_0199
./mc/prefiltered_func_data_mcf.mat/MAT_0200
./mc/prefiltered_func_data_mcf.mat/MAT_0201
./mc/prefiltered_func_data_mcf.mat/MAT_0202
./mc/prefiltered_func_data_mcf.mat/MAT_0203
./mc/prefiltered_func_data_mcf.mat/MAT_0204
./mc/prefiltered_func_data_mcf.mat/MAT_0205
./mc/prefiltered_func_data_mcf.mat/MAT_0206
./mc/prefiltered_func_data_mcf.mat/MAT_0207
./mc/prefiltered_func_data_mcf.mat/MAT_0208
./mc/prefiltered_func_data_mcf.mat/MAT_0209
./mc/prefiltered_func_data_mcf.mat/MAT_0210
./mc/prefiltered_func_data_mcf.mat/MAT_0211
./mc/prefiltered_func_data_mcf.mat/MAT_0212
./mc/prefiltered_func_data_mcf.mat/MAT_0213
./mc/prefiltered_func_data_mcf.mat/MAT_0214
./mc/prefiltered_func_data_mcf.mat/MAT_0215
./mc/prefiltered_func_data_mcf.mat/MAT_0216
./mc/prefiltered_func_data_mcf.mat/MAT_0217
./mc/prefiltered_func_data_mcf.mat/MAT_0218
./mc/prefiltered_func_data_mcf.mat/MAT_0219
./mc/prefiltered_func_data_mcf.mat/MAT_0220
./mc/prefiltered_func_data_mcf.mat/MAT_0221
./mc/prefiltered_func_data_mcf.mat/MAT_0222
./mc/prefiltered_func_data_mcf.mat/MAT_0223
./mc/prefiltered_func_data_mcf.mat/MAT_0224
./mc/prefiltered_func_data_mcf.mat/MAT_0225
./mc/prefiltered_func_data_mcf.mat/MAT_0226
./mc/prefiltered_func_data_mcf.mat/MAT_0227
./mc/prefiltered_func_data_mcf.mat/MAT_0228
./mc/prefiltered_func_data_mcf.mat/MAT_0229
./mc/prefiltered_func_data_mcf.par
./mc/prefiltered_func_data_mcf_abs.rms
./mc/prefiltered_func_data_mcf_abs_mean.rms
./mc/prefiltered_func_data_mcf_rel.rms
./mc/prefiltered_func_data_mcf_rel_mean.rms
./mc/rot.png
./mc/trans.png
./mc/disp.png
./mean_func.nii.gz
./mask.nii.gz
./filtered_func_data.nii.gz
./absbrainthresh.txt
./report_prestats.html
./report.html

**Comment by maartenmennes** [comment]
yes, always run ICA-AROMA by specifying full paths to your files e.g., /home/me/mydata/sub001/preprocessing/filtered_func_data.nii.gz instead of filtered_func_data.nii.gz, even if you run it from the folder where the data is.
