### ISSUE TITLE
Too many noisy components

### ISSUE THREAD

**Issue by joseappardo** [maartenmennes/ICA-AROMA#41]
Hi,

I have run ICA Aroma within the fMRIprep, and after reviewing the components summary, I am finding that there are many noisy components (70-80%). In principle this should not be a problem but I see that there are several noisy components that are classified as useful signal, and the opposite. For example below, the C22, I do not understand why it is classified as noise

![Screenshot from 2019-07-18 19-17-51](https://user-images.githubusercontent.com/51779368/61526847-85f86c00-aa1b-11e9-9415-c727adedbcb5.png)

Or this C45

![Screenshot from 2019-07-18 19-19-05](https://user-images.githubusercontent.com/51779368/61526891-97417880-aa1b-11e9-8bb4-7c46a6c8bc08.png)

Furthermore I am also seeing the opposite, that for example two components that seem to be RF noise are classified as signal

![Screenshot from 2019-07-18 19-20-14](https://user-images.githubusercontent.com/51779368/61527005-c6f08080-aa1b-11e9-8158-42b91b276121.png)

My question is whether this is a consequence of limited quality in the data, whether I should reduce the number of components let's say to 40, or if I should do a manual selection per subject.

Many thanks for your help and for the tool.

Best
José

**Comment by maartenmennes** [comment]
Hello,
wrt components that you think are signal but are classified as noise: using the figures in  ICA_AROMA_component_assessment.pdf and the classification_overview.txt file you can see exactly why they were classified as noise.

wrt to components that are not classified as noise but should be according to you: please remember that ICA AROMA is specifically geared towards detecting artifacts related to head motion (the frequency and CSF criteria are essentially safe options for some extra denoising on the side). Accordingly, AROMA has not been trained to detect RF noise. If you wish to remove this from your data, then it is best to either resort to manual classification or use ICA-FIX which you can train to detect such noise sources.

It is not uncommon to find 70-80% of your components being classified as noise... that said, finding one such subject in your dataset (while all others have a lower number of components flagged) should be a trigger for further investigation into the specifics of that dataset.
