### ISSUE TITLE
Is there a plan to move to python3?

### ISSUE THREAD

**Issue by yaowang1111** [maartenmennes/ICA-AROMA#44]
Hi, just wondering if moving to python3 is planed, because it's inefficient for the user to maitain two environments. Thanks.

**Comment by WillForan** [comment]
I'm using @rtrhd's fork like `pip install git+https://github.com/rtrhd/ICA-AROMA` for a python3 ica-aroma in the interim

**Comment by yaowang1111** [comment]
Thanks!

**Comment by maartenmennes** [comment]
If I'm correct the current code is python3 compatible as it is. see commit https://github.com/maartenmennes/ICA-AROMA/commit/67aac4b5d5fa46b4b5c46ef26f2e4f75af004e17

I anticipate better knowledge of this, when I finally make the switch too 😟
