### ISSUE TITLE
ICA AROMAerror while running

### ISSUE THREAD

**Issue by neer86** [maartenmennes/ICA-AROMA#46]
Whie Running ICA AROMA after running the preprocessing using FSL feat. I got the following error. Could you please guide me for the possible solutions :+1: ------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
  - The existing/specified MELODIC directory will be used.
  - The MELODIC directory does not contain the required 'stats' folder. Mixture modeling on the Z-statistical maps will be run.
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
Traceback (most recent call last):
  File "/home/upadhyayn/ICA-AROMA/ICA_AROMA.py", line 221, in <module>
    HFC = aromafunc.feature_frequency(melFTmix, TR)
  File "/home/upadhyayn/ICA-AROMA/ICA_AROMA_functions.py", line 329, in feature_frequency
    idx_cutoff = np.argmin(np.abs(fcumsum_fract - 0.5), axis=0)
  File "/home/upadhyayn/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1068, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/home/upadhyayn/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

Best Regards

**Comment by maartenmennes** [comment]
this error is shown when all components are labelled as noise. If this happens something is not right with your data.
