### ISSUE TITLE
Drifts/Detrending 

### ISSUE THREAD

**Issue by asoroosh** [maartenmennes/ICA-AROMA#48]
I was wondering whether the ICA-AROMA is suggested to be applied after or before detreding? or it doesn't matter? My intuition is that it should be applied *after* removing the drifts. 

Thank you so much in advance, 

PS. 
By detredning, I mean the high pass filter (in FSL FEAT), DCT in SPM and Poly in AFNI.

**Comment by maartenmennes** [comment]
yes, AROMA is intended to be applied after highpass filtering.
