### ISSUE TITLE
ICA-AROMA cannot find feat directory

### ISSUE THREAD

**Issue by leightjt** [maartenmennes/ICA-AROMA#52]
Hi,

I've run ICA_AROMA and it aborts with this error message:

MacBook-Pro:Desktop user$ python ICA-AROMA-master/ICA_AROMA.py -feat rs_baseline_preprocessing.feat -out rs_baseline_preprocessing.feat/ICA-AROMA

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

The specified Feat directory does not exist.

----------------------------- ICA-AROMA IS CANCELED -----------------------------

The ICA-AROMA-master and rs_baseline_preprocessing.feat folder are on my Desktop.

Would appreciate any advice!

Leigh

**Comment by maartenmennes** [comment]
hello,
AROMA only works when you provide the full path. e.g., /home/me/mystudy/subject001/rest_01/rest_01.feat
cheers,
Maarten
