### ISSUE TITLE
WM regression after ICA-AROMA

### ISSUE THREAD

**Issue by s2334** [maartenmennes/ICA-AROMA#55]
The original ICA-AROMA paper recommends smoothing the data prior to ICA-AROMA and then running additional denoising on ICA-AROMA output, such as regressing out WM, CSF. 
 
So I ran ICA-AROMA like so:
ICA_AROMA.py -in func_smoothed.nii.gz -out nonaggr_func.nii.gz -mc mc/rest_mcf.par -affmat reg/example_func2highres.mat -warp reg/highres2standard_warp.nii.gz -m mask_aroma.nii.gz

and then extracted the mean WM signal with:
fslmeants -i nonaggr_func.nii.gz -o WM_signal.txt -m WM_mask.nii.gz

However, isn't it a problem that WM mean signal is being extracted from smoothed data?

**Comment by maartenmennes** [comment]
Why would that be a problem? All other data extraction (e.g., a seed region) would also be from the smoothed data. The brain is not organized in voxels, that is why we apply smoothing. Key is not to smooth with an excessively large kernel (we recommend 1.5x the voxelsize). 

Further, you want to make sure your WM and CSF masks are correctly and tightly defined. It's better to have smaller masks, so you can be sure that the signal you extract is most definitely coming from WM or CSF.

**Comment by s2334** [comment]
Thank you very much for your reply @maartenmennes. 
The reason I asked was because I fear partial volume effects if I extract the WM from the smoothed functional data. 
Maybe I'm wrong, but I think it was suggested in a [neurostars post](https://neurostars.org/t/fmriprep-ica-aroma-filtering-including-wm-csf-etc-confounds-in-fsl-regfilt/3137/3) that masks should not be extracted from smoothed images, is that right @jdkent? But I agree that with an accurate WM mask this shouldn't be much of a problem.

**Comment by maartenmennes** [comment]
> But I agree that with an accurate WM mask this shouldn't be much of a problem.

exactly, in fact, it shouldn't be a problem at all. We typically use a 95% probability threshold on the prior maps for WM and CSF before multiplying them with the subject-specific segmentation maps in order to create the masks.
