### ISSUE TITLE
nonaggr denoising after ICA-AROMA

### ISSUE THREAD

**Issue by s2334** [maartenmennes/ICA-AROMA#56]
I'm doing seed-based connectivity analysis and I would like to perform non-aggressive denoising. I'm using the denoised_func_data_nonaggr.nii.gz output from ICA-AROMA as the input functional data in my first level analysis. 

For the first level design matrix should I include any other ICA-AROMA output in addition to the other nuisance variables and seed regressors? Or is the denoised_func_data_nonaggr data already corrected for motion, so there is no need to include additional motion-related noise components/regressors?

Also, I'm finding about half of the components are identified as noise. Is this to be expected? What is a reasonable number of noise components?

**Comment by maartenmennes** [comment]
>  Or is the denoised_func_data_nonaggr data already corrected for motion, so there is no need to include additional motion-related noise components/regressors?

Correct

> Also, I'm finding about half of the components are identified as noise. Is this to be expected? What is a reasonable number of noise components?

This is a typical number. We find that up to 80% of components can be identified as motion-related noise.
