### ISSUE TITLE
ICA-AROMA error

### ISSUE THREAD

**Issue by tayebehebrahimi64** [maartenmennes/ICA-AROMA#61]
Hi,
I am using ICA_AROMA to analyse some fmri data. version of fsl is 6.0.5.1 and version of python is 3.9.8 and version of ICA-AROMA is 0.4.4. I successfully ran FEAT, but when I run  python ICA_AROMA.py to do MELODIC, in the step 1) I receive huge similar error about fslroi.
[tinabrah@i17 ICA-AROMA-master]$ python ICA_AROMA.py -in /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/filtered_func_data.nii.gz -out /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/ICA_AROMA -affmat /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/reg/example_func2highres.mat -warp /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/reg/highres2standard_warp.nii.gz -mc /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/mc/prefiltered_func_data_mcf.par

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC

Usage: fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize>
       fslroi <input> <output> <tmin> <tsize>

       fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize> <tmin> <tsize>
Note: indexing (in both time and space) starts with 0 not 1! Inputting -1 for a size will set it to the full image extent for that dimension.
sh: line 1: 01: command not found

Usage: fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize>
       fslroi <input> <output> <tmin> <tsize>

       fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize> <tmin> <tsize>
Note: indexing (in both time and space) starts with 0 not 1! Inputting -1 for a size will set it to the full image extent for that dimension.
sh: line 1: 02: command not found

Usage: fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize>
       fslroi <input> <output> <tmin> <tsize>

       fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize> <tmin> <tsize>
Note: indexing (in both time and space) starts with 0 not 1! Inputting -1 for a size will set it to the full image extent for that dimension.
sh: line 1: 03: command not found

Usage: fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize>
       fslroi <input> <output> <tmin> <tsize>

       fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize> <tmin> <tsize>
Note: indexing (in both time and space) starts with 0 not 1! Inputting -1 for a size will set it to the full image extent for that dimension.

and after 100 error related to fslroi, at the end I receive this error:

sh: line 1: 0100: command not found
Image Exception : #63 :: No image files match: /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/ICA_AROMA/thr_zstat????
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/ICA_AROMA/thr_zstat????
rm: cannot remove ‘/N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/ICA_AROMA/thr_zstat????.nii.gz’: No such file or directory
Image Exception : #63 :: No image files match: /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/ICA_AROMA/melodic_IC_thr
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /N/project/dMRI1/CARE_CSI/ANALYSIS/n-back/test/Task.feat/ICA_AROMA/melodic_IC_thr

Could you please help me to fix this error?

Thank you
Tina

**Comment by maartenmennes** [comment]
Hello, it looks like your melodic decomposition did not complete correctly? Was a melodic.ica folder created in your ICA_AROMA folder? What does the log.txt file in that folder say? Can you open the report/00_index.html file and see what that looks like?
