### ISSUE TITLE
Error: Mask and image must be the same size

### ISSUE THREAD

**Issue by parmisk** [maartenmennes/ICA-AROMA#69]
Hi, I am runing the ICA AROMA on fMRIprep outputs and am getting the following errors:
(I am using MNI152NLin2009cAsym space). Would appreciate your help. 

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
Traceback (most recent call last):
  File "/data/NNT/fox-flanker/code/ICA-AROMA-master/ICA_AROMA.py", line 213, in <module>
    edgeFract, csfFract = aromafunc.feature_spatial(fslDir, outDir, scriptDir, melIC_MNI)
  File "/vf/users/NNT/fox-flanker/code/ICA-AROMA-master/ICA_AROMA_functions.py", line 400, **in feature_spatial
    '-V | awk \'{print $1}\''])))**
**ValueError: invalid literal for int() with base 10: 'Mask and image must be the same size'**

**Comment by maartenmennes** [comment]
Hello, I'm not fully up to date with the fmriprep implementation, but the error message suggests that the MN152NLin2009cAsym space has a different matrix dimension compared to the typical MNI152 space 2mm we use in AROMA (91x109x91).

**Comment by parmisk** [comment]
Thank you for getting back to me so quickly. I checked and the MN152NLin2009cAsym matches the dimensions you stated res = 2 mm (91x109x91).  Is there any other reason that this error would occur since our template has the same matrix dimension? Also, I used the ICA-AROMA script you have on your page since fMRIprep no longer supports AROMA within their workflow.

**Comment by parmisk** [comment]
Please ignore my last email, I ended up re-runing the fMRIprep with the MNI152NLin6Asym to match what AROMA requires and it worked. Thank you.
